name: Site_Of_R
description: rhapsodyn's blog
meta_description: rhapsodyn's blog
timezone: Asia/Shanghai

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: http://www.rhapsodyn.com
author: rhapsodyn
